In [1]:
import torch

In [51]:
torch.__version__

'2.3.1+cu121'

Lettura della documentazione - Leggere la documentazione torch.Tensor e di torch.cuda per poter eseguire quanto visto in questa lezione su GPU.

Crea un vettore casuale con dimensione (5, 5).

Esegui una moltiplicazione tra matrici tra in tensore creato nel punto 2 con un'altro tensore di dimensione (1, 5) (attento alle dimensioni!).

Fissa il seed al numero 15 e ripeti i punti 2 e 3 diverse volte.

Inizializza la GPU e assicurati che stia funzionando

Crea due tensori casuali di dimensioni (2, 4) e caricale su GPU.

Esegui una moltiplicazione tra matrici tra i tensori creati nel punto 6.

Trova il massimo e il minimo dell'output del punto 7.

Trova gli indici del valore massimo e minimo dell'output del punto 7 (non abbiamo visto questo metodo, è il momento di verificare la vostra comprensione della documentazione!).

Crea un tensore casuale con shape (1, 1, 1, 8), comprimilo rimuovendo tutte le dimensioni 1, poi riportalo alla dimensione originale.

In [3]:
cuda = torch.device('cuda')   

cuda

device(type='cuda')

In [12]:
a = torch.tensor([1., 2.])
print(a)

with cuda:
    # This will run on the GPU

    b = torch.tensor([1., 2.])
    print(b)

    c = torch.tensor([[1., 2.], [3., 4.]])
    print(c)

    d = torch.matmul(b, c)
    print(d)

tensor([1., 2.])
tensor([1., 2.], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
tensor([ 7., 10.], device='cuda:0')


In [52]:
# set seed for reproducibility
torch.manual_seed(15)

a = torch.rand(5,5)

b = torch.rand(1,5)

print(torch.matmul(a, b.T))

tensor([[0.5523],
        [0.7028],
        [0.7011],
        [1.0323],
        [0.6487]])


In [28]:
a = torch.rand(2,4)

b = torch.rand(2,4)

a = a.to(cuda)
b = b.to(cuda)

print(a, b)

tensor([[0.0638, 0.6259, 0.2381, 0.8058],
        [0.8173, 0.4486, 0.5437, 0.7319]], device='cuda:0') tensor([[0.6628, 0.8740, 0.4006, 0.1980],
        [0.2682, 0.4487, 0.4928, 0.7281]], device='cuda:0')


In [30]:
c = torch.mul(a, b)

print(torch.max(c), torch.min(c))
print(torch.mean(c))

tensor(0.5470, device='cuda:0') tensor(0.0423, device='cuda:0')
tensor(0.2582, device='cuda:0')


In [42]:
# returning indexes of max and min

tensor = torch.tensor([[1., 2.], [3., 4.]])

val, index = torch.max(tensor, dim=1)

index

tensor([1, 1])

In [50]:
tensor = torch.rand(1,1,1,8)

for i in range(3):
    tensor = torch.squeeze(tensor, dim=0) 

tensor.shape

torch.Size([8])

In [ ]:
tensor = tensor.to(cuda)
tensor.device

device(type='cuda', index=0)